/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@mixin blind-font {\n  font:0/0 "Noto Sans KR";\n}\n\n.paginate[_ngcontent-%COMP%] {\n  text-align:center;\n  padding:10px 0;\n  @include blind-font;\n  a {\n    display:inline-block;\n    width:30px;\n    height:30px;\n    text-align:center;\n    font-size:15px;\n    line-height:30px;\n    cursor: pointer;\n    vertical-align: middle;\n  }\n  strong {\n    display:inline-block;\n    width:30px;\n    height:30px;\n    text-align:center;\n    font-size:15px;\n    line-height:30px;\n    cursor: pointer;\n    vertical-align: middle;\n    border:1px solid #fcd20c;\n    font-size:15px;\n    line-height:26px;\n  }\n  .button-prev {\n    @include blind-font;\n    background: url(\'/assets/images/icon/ico-paginate-prev.png\') 50% 50% no-repeat;\n  }\n  .button-next {\n    @include blind-font;\n    background: url(\'/assets/images/icon/ico-paginate-next.png\') 50% 50% no-repeat;\n  }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvaG9keXMvd29ya3NwYWNlL25nLXNpbXBsZUdyaWQvc3JjL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jb21wb25lbnQuc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2hvZHlzL3dvcmtzcGFjZS9uZy1zaW1wbGVHcmlkL3NyYy9wYWdpbmF0aW9uL3BhZ2luYXRpb24uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
