/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './grid.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '../pagination/pagination.module';
class GridModuleInjector extends import0.ɵNgModuleInjector<import1.GridModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _ReactiveFormsModule_2:import3.ReactiveFormsModule;
  _PaginationModule_3:import4.PaginationModule;
  _GridModule_4:import1.GridModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __FormBuilder_6:import3.FormBuilder;
  __ɵi_7:import3.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _FormBuilder_6():import3.FormBuilder {
    if ((this.__FormBuilder_6 == null)) { (this.__FormBuilder_6 = new import3.FormBuilder()); }
    return this.__FormBuilder_6;
  }
  get _ɵi_7():import3.ɵi {
    if ((this.__ɵi_7 == null)) { (this.__ɵi_7 = new import3.ɵi()); }
    return this.__ɵi_7;
  }
  createInternal():import1.GridModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._ReactiveFormsModule_2 = new import3.ReactiveFormsModule();
    this._PaginationModule_3 = new import4.PaginationModule();
    this._GridModule_4 = new import1.GridModule();
    return this._GridModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import4.PaginationModule)) { return this._PaginationModule_3; }
    if ((token === import1.GridModule)) { return this._GridModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.FormBuilder)) { return this._FormBuilder_6; }
    if ((token === import3.ɵi)) { return this._ɵi_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GridModuleNgFactory:import0.NgModuleFactory<import1.GridModule> = new import0.NgModuleFactory<any>(GridModuleInjector,import1.GridModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvaG9keXMvd29ya3NwYWNlL25nLXNpbXBsZUdyaWQvc3JjL2dyaWQvZ3JpZC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9ob2R5cy93b3Jrc3BhY2Uvbmctc2ltcGxlR3JpZC9zcmMvZ3JpZC9ncmlkLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
